name: PR Approval Workflow

on:
  pull_request:
    branches:
      - StagingRelease*
  pull_request_review:
    types: [submitted]

jobs:
  check-approvals:
    if: startsWith(github.event.pull_request.base.ref, 'StagingRelease')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: read
    steps:
      - name: Check for required approvals
        id: check-approvals
        uses: skymoore/required-approvals@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          read_org_scoped_token: ${{ secrets.READ_ORG_SCOPED_TOKEN }}
          org_name: reederected
          min_approvals: 1

      - name: Run action if all required approvals are met
        if: ${{ steps.check-approvals.outputs.approved == 'true' }}
        run: |
          echo "All required approvals are met. Running the action."
