name: PR Approval Workflow

on:
  pull_request_review:
    types: [submitted]

jobs:
  check-approvals:
    if: >-
      startsWith(github.event.pull_request.base.ref, 'StagingRelease') ||
      startsWith(github.event.pull_request.base.ref, 'LiveRelease')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: read
    steps:
      - name: Check for required approvals
        id: check-approvals
        uses: mreeder/required-approvals@v1-beta
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          read_org_scoped_token: ${{ secrets.READ_ORG_SCOPED_TOKEN }}
          org_name: reederected
          min_approvals: 1
