name: "PR Title Check"
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  check-ticket-is-in-title:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR title
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const payload = context.payload
          const prTitle = payload.pull_request.title
          // The pattern for JIRA ticket format
          const jiraPattern = /^(ORDEV|DEVOPS|ITOP)-\d+/g
          if (!jiraPattern.test(prTitle)) {
            console.log('The PR title does not match JIRA ticket format!')
            // Fails the workflow
            core.setFailed('PR title does not match JIRA ticket format!')
          } else {
            console.log('PR title format is correct.')
          }
